theme: minima
title: Color with Chill
author: Chieu Nhat Le
description: |
  Learn the rules of color with Chill, we will learn together how the colorwheel coordinates different colors. 
  Besides, we will find out the reason why there are different colors.
  At the same time, what is wavelength and how can scientists determine it?
